<!DOCTYPE html>
<html lang="en"><head>
<script src="wdi_report_files/libs/clipboard/clipboard.min.js"></script>
<script src="wdi_report_files/libs/quarto-html/tabby.min.js"></script>
<script src="wdi_report_files/libs/quarto-html/popper.min.js"></script>
<script src="wdi_report_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="wdi_report_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="wdi_report_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="wdi_report_files/libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.8.25">

  <meta name="author" content="AC">
  <meta name="dcterms.date" content="2025-10-06">
  <title>World Development Indicators (2022) Report</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="wdi_report_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="wdi_report_files/libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for citations */
    div.csl-bib-body { }
    div.csl-entry {
      clear: both;
      margin-bottom: 0em;
    }
    .hanging-indent div.csl-entry {
      margin-left:2em;
      text-indent:-2em;
    }
    div.csl-left-margin {
      min-width:2em;
      float:left;
    }
    div.csl-right-inline {
      margin-left:2em;
      padding-left:1em;
    }
    div.csl-indent {
      margin-left: 2em;
    }  </style>
  <link rel="stylesheet" href="wdi_report_files/libs/revealjs/dist/theme/quarto-534cd8e3a96973385dffff3f4709048d.css">
  <link href="wdi_report_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="wdi_report_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="wdi_report_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="wdi_report_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">World Development Indicators (2022) Report</h1>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
AC 
</div>
</div>
</div>

  <p class="date">2025-10-06</p>
</section>
<section id="introduction" class="slide level2">
<h2>Introduction</h2>
<p>The <em>World Development Indicators</em> (WDI) dataset, compiled by the World Bank, provides a comprehensive collection of internationally comparable statistics about global development <span class="citation" data-cites="worldbank2022">(<a href="#/references" role="doc-biblioref" onclick="">World Bank, 2022</a>)</span>. It covers a wide range of dimensions, including economic performance, education, health, and social progress, enabling researchers and policymakers to assess development outcomes across countries and over time. This report focuses on a 2022 cross-sectional sample of the WDI data containing 14 key socioeconomic variables for countries worldwide.</p>
<p>Among these variables, particular attention is given to three core indicators that capture critical aspects of human capital and development:</p>
<ol type="1">
<li><p><strong>Education expenditure (% of GDP)</strong> : representing the share of national output devoted to education sector.</p></li>
<li><p><strong>Health expenditure (% of GDP)</strong> : indicating the proportion of GDP spent on healthcare sector.</p></li>
<li><p><strong>Life expectancy (in years)</strong> : measuring the average number of years a newborn is expected to live under current mortality conditions.</p></li>
</ol>
<p>These indicators are often interlinked: education investment can influence health awareness and employment opportunities, while health spending directly impacts life expectancy through improvements in healthcare quality and accessibility. Analyzing the relationship among these variables provides insights into how nations allocate resources to human development and how these investments translate into population outcomes. We hope that this analysis could highlight disparities, potential correlations, and data gaps that may inform future studies on the effectiveness of social spending in enhancing human welfare.</p>
</section>
<section id="exploratory-data-analysis" class="slide level2">
<h2>Exploratory Data Analysis</h2>
<h3 id="education-expenditure-as-a-share-of-gdp">Education Expenditure as a Share of GDP</h3>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>**Summary Statistics for Education Expenditure (% of GDP):**</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
  1.027   2.898   3.887   4.226   5.156  16.582     112 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
**Missing Values:** 112 countries</code></pre>
</div>
</div>
<ul>
<li><strong>Analysis</strong>: The distribution appears skewed, with most countries spending between 2-5% of GDP on education, as indicated by the interquartile range (2.898% to 5.156%) and the median of 3.887%. The mean (4.226%) is slightly higher than the median, suggesting the presence of outliers, with Namibia at 9.678% and a maximum of 16.582% driving the upper tail. The variability highlights differing national priorities in educational investment. The 112 missing values (over a third of the dataset) limit the analysis, potentially skewing the overall picture. Countries with higher expenditures, like Namibia, may prioritize education to boost literacy and economic growth, while those with lower spending might face resource constraints or different policy focuses.</li>
</ul>
<h3 id="health-expenditure-as-a-share-of-gdp">Health Expenditure as a Share of GDP</h3>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>**Summary Statistics for Health Expenditure (% of GDP):**</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
  5.100   7.263   8.925   9.044  10.633  16.571     197 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
**Missing Values:** 197 countries</code></pre>
</div>
</div>
<ul>
<li><strong>Analysis</strong>: Health expenditure varies widely across countries, with the U.S. at 16.571% standing out as a significant outlier, indicating a substantial investment compared to others. The mean (9.044%) is slightly higher than the median (8.925%), suggesting a right-skewed distribution possibly influenced by high-spending outliers like the U.S. The median suggests that most countries allocate around 8-9% of GDP to health, but the presence of 197 missing values (a large portion of the dataset) limits the comprehensiveness of this analysis. Higher spending might correlate with better healthcare infrastructure, as seen in countries with advanced medical systems, though the missing data obscures a complete picture. More research should be conducted in the future.</li>
</ul>
<h3 id="life-expectancy">Life Expectancy</h3>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>**Summary Statistics for Life Expectancy (Years):**</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
  53.00   66.78   73.51   72.42   78.47   85.38       8 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
**Missing Values:** 8 countries</code></pre>
</div>
</div>
<ul>
<li><strong>Analysis</strong>: Life expectancy ranges widely, from 53.00 years (likely reflecting countries with significant health or economic challenges) to 85.38 years (indicative of high-living-standard nations). The median (73.51 years) is close to the mean (72.42 years), suggesting a relatively symmetric distribution, though the lower minimum pulls the mean slightly down. The interquartile range (66.78 to 78.47 years) shows that 50% of countries have life expectancies between these values, reflecting moderate global health outcomes. With only 8 missing values, this indicator is more reliable than health expenditure data. The variation suggests that factors beyond health expenditure, such as nutrition, sanitation, and education, also play critical roles in determining life expectancy.</li>
</ul>
<h3 id="visualizations">Visualizations</h3>
<h4 id="bar-chart-top-10-by-education-spending-share">Bar chart (Top 10 by education spending share)</h4>
<div class="cell">
<div class="cell-output-display">
<div id="fig-edu-top10" class="quarto-float quarto-figure quarto-figure-center">
<figure class="quarto-float quarto-float-fig">
<div aria-describedby="fig-edu-top10-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img data-src="wdi_report_files/figure-revealjs/fig-edu-top10-1.png" width="768">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-edu-top10-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Top 10 countries by education expenditure as a share of GDP (2022). Source: World Development Indicators (wdi.csv).
</figcaption>
</figure>
</div>
</div>
</div>
<p><a href="#/fig-edu-top10" class="quarto-xref">Figure&nbsp;1</a> highlights the top 10 countries by education expenditure as a share of GDP in 2022, with Kiribati leading at the highest percentage and Marshall Islands at the lowest among the top 10. The range shows significant variation, with Namibia and Sierra Leone also featuring prominently, suggesting that small or developing nations may prioritize education spending, possibly to address literacy or economic development needs.</p>
<h4 id="scatter-plot-health-spending-share-vs.-life-expectancy">Scatter plot (Health spending share vs.&nbsp;Life expectancy)</h4>
<div class="cell">
<div class="cell-output-display">
<div id="fig-health-life" class="quarto-float quarto-figure quarto-figure-center">
<figure class="quarto-float quarto-float-fig">
<div aria-describedby="fig-health-life-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img data-src="wdi_report_files/figure-revealjs/fig-health-life-1.png" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-health-life-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Health expenditure (% of GDP) vs.&nbsp;life expectancy (years), 2022. Line shows linear fit. Source: World Development Indicators (wdi.csv).
</figcaption>
</figure>
</div>
</div>
</div>
<p><a href="#/fig-health-life" class="quarto-xref">Figure&nbsp;2</a> indicates a weak positive association between health expenditure (% of GDP) and life expectancy in 2022, with countries allocating more to health tending to have higher average life expectancy. The relationship is noisy, as evidenced by outliers like the U.S, due to influences from absolute income, demographics, health-system efficiency, and lifestyle factors. However, with 197 missing values for health expenditure in this dataset, the fitted line should be interpreted cautiously, reflecting only partial data coverage.</p>
<h3 id="summary-table">Summary Table</h3>
<div class="cell">
<div id="tbl-key-stats" class="cell quarto-float quarto-figure quarto-figure-center">
<figure class="quarto-float quarto-float-tbl">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-key-stats-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Key statistics for 2022 indicators. Source: World Development Indicators (wdi.csv).
</figcaption>
<div aria-describedby="tbl-key-stats-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top">
<colgroup>
<col style="width: 44%">
<col style="width: 10%">
<col style="width: 11%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 13%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Indicator</th>
<th style="text-align: center;">Mean</th>
<th style="text-align: center;">Median</th>
<th style="text-align: center;">Min</th>
<th style="text-align: center;">Max</th>
<th style="text-align: center;">Missing</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Education Expenditure (% GDP)</td>
<td style="text-align: center;">4.23</td>
<td style="text-align: center;">3.89</td>
<td style="text-align: center;">1.03</td>
<td style="text-align: center;">16.58</td>
<td style="text-align: center;">112</td>
</tr>
<tr class="even">
<td style="text-align: center;">Health Expenditure (% GDP)</td>
<td style="text-align: center;">9.04</td>
<td style="text-align: center;">8.93</td>
<td style="text-align: center;">5.10</td>
<td style="text-align: center;">16.57</td>
<td style="text-align: center;">197</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Life Expectancy (Years)</td>
<td style="text-align: center;">72.42</td>
<td style="text-align: center;">73.51</td>
<td style="text-align: center;">53.00</td>
<td style="text-align: center;">85.38</td>
<td style="text-align: center;">8</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
</section>
<section id="analysis" class="slide level2">
<h2>Analysis</h2>
<p>The analysis of global development indicators reveals distinct patterns in education and health investments across countries. As shown in <a href="#/fig-edu-top10" class="quarto-xref">Figure&nbsp;1</a>, the top ten countries by education expenditure as a share of GDP in 2022 exhibit considerable variation, with Kiribati leading the list and several small or developing nations allocating relatively large proportions of GDP to education, suggesting a prioritization of human-capital development within these regions, potentially reflecting efforts to strengthen literacy and expand access to schooling despite limited fiscal capacity. However, since these figures represent spending shares rather than educational outcomes, the link between higher expenditure and improved quality remains uncertain.</p>
<p>Empirical research supports the positive impact of educational investment on economic and social development. The World Bank reports that each additional year of schooling increases individual earnings by approximately 10 %, underscoring the long-term value of sustained investment in education <span class="citation" data-cites="worldbankblog">(<a href="#/references" role="doc-biblioref" onclick="">Harry A. Patrinos, 2023</a>)</span>. Similarly, the Learning Policy Institute finds that greater educational funding, particularly for low-income populations, correlates with higher academic achievement and graduation rates <span class="citation" data-cites="lpi">(<a href="#/references" role="doc-biblioref" onclick="">Learning Policy Institute, 2024</a>)</span>. Nonetheless, as our data indicate, many countries spend below 4 % of GDP on education, highlighting a global investment gap. Moreover, even among high-spending nations, small economies may appear to allocate substantial shares of GDP despite having modest per-student budgets, complicating cross-country comparisons.</p>
<p>The relationship between health expenditure and life expectancy, visualized in <a href="#/fig-health-life" class="quarto-xref">Figure&nbsp;2</a>, shows a weak positive association. Countries that allocate a greater proportion of GDP to health generally exhibit longer life expectancies, but the correlation remains moderate and influenced by outliers such as the United States (16.57 % of GDP, 77.43 years). The analysis is further limited by data coverage, with 197 missing values for health expenditure. These results suggest that while financial investment in health is important, system efficiency, preventive care, and equitable infrastructure play equally significant roles. The University of Michigan’s global health factsheet <span class="citation" data-cites="umich">(<a href="#/references" role="doc-biblioref" onclick="">Center for Sustainable Systems, University of Michigan, 2025</a>)</span> reinforces this interpretation, reporting that in 2022, 1.5 billion people lacked access to basic sanitation, and that safe drinking water coverage remained below 30 % in low-income countries. Improvements in sanitation, water access, and preventive healthcare often yield greater longevity gains than increased spending alone.</p>
<p>A statistical summary of these indicators is provided in <a href="#/tbl-key-stats" class="quarto-xref">Table&nbsp;1</a>, which illustrates the wide range in global life expectancy (from 53.00 to 85.38 years) and underscores the limited data availability for health expenditure. This uneven coverage suggests that the current dataset may overrepresent higher-income countries with stronger reporting systems, potentially biasing the observed averages.</p>
<p>Further analysis could compare these indicators across regions or income groups, as suggested by the data in <a href="#/fig-health-life" class="quarto-xref">Figure&nbsp;2</a> and <a href="#/tbl-key-stats" class="quarto-xref">Table&nbsp;1</a>. For instance, the weak overall correlation between health spending and life expectancy may conceal stronger associations in developed economies with mature healthcare infrastructures and weaker or nonlinear patterns in developing contexts. Including additional metrics, such as per-capita spending, education quality indices, or healthcare accessibility measures, would allow for a more nuanced assessment of how national investments translate into human well-being.</p>
</section>
<section id="insights-and-future-implications" class="slide level2">
<h2>Insights and Future Implications</h2>
<ul>
<li><p><em>The top ten education spenders are predominantly small or developing nations, indicating that percentage-of-GDP metrics can overstate investment intensity in economies with small GDP bases.</em></p></li>
<li><p><em>The weak but positive relationship between health expenditure and life expectancy supports the view that financial inputs are necessary but insufficient; system design and efficiency are crucial determinants of outcomes.</em></p></li>
<li><p><em>The high level of missing data, particularly for health expenditure, highlights an urgent need for improved international reporting standards to enable more representative global comparisons.</em></p></li>
<li><p><em>The modest correlation between education expenditure and life expectancy likely reflects the influence of broader structural factors such as income, sanitation, and healthcare access.</em></p></li>
</ul>
<p>Overall, we believe that these findings indicate that increasing spending alone is insufficient to achieve equitable development outcomes. Policymakers could focus more on enhancing the efficiency and quality of education and health investments. In education, this entails prioritizing early childhood and basic education, ensuring that funding translates into teacher training, learning materials, and equitable access. In the health sector, governments could strengthen preventive care, primary healthcare systems, and sanitation infrastructure, which have been shown to yield greater improvements in life expectancy than curative spending alone. Finally, global development agencies should invest in data transparency and consistency, particularly in low- and middle-income countries, to support evidence-based policymaking and monitor progress toward the sustainable goals.</p>
</section>
<section id="references" class="slide level2 smaller scrollable">
<h2>References</h2>
<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list">
<div id="ref-umich" class="csl-entry" role="listitem">
Center for Sustainable Systems, University of Michigan. (2025). <em>Social development indicators factsheet</em>. University of Michigan. <a href="https://css.umich.edu/publications/factsheets/sustainability-indicators/social-development-indicators-factsheet">https://css.umich.edu/publications/factsheets/sustainability-indicators/social-development-indicators-factsheet</a>
</div>
<div id="ref-worldbankblog" class="csl-entry" role="listitem">
Harry A. Patrinos. (2023). <em>Investing in tomorrow: How educational spending translates into lifelong returns</em>. World Bank Blogs. <a href="https://blogs.worldbank.org/en/education/investing-tomorrow-how-educational-spending-translates-lifelong-returns">https://blogs.worldbank.org/en/education/investing-tomorrow-how-educational-spending-translates-lifelong-returns</a>
</div>
<div id="ref-lpi" class="csl-entry" role="listitem">
Learning Policy Institute. (2024). <em>How money matters: The facts</em>. Learning Policy Institute. <a href="https://learningpolicyinstitute.org/product/how-money-matters-factsheet">https://learningpolicyinstitute.org/product/how-money-matters-factsheet</a>
</div>
<div id="ref-worldbank2022" class="csl-entry" role="listitem">
World Bank. (2022). <em>World development indicators database</em>. World Bank. <a href="https://databank.worldbank.org/source/world-development-indicators">https://databank.worldbank.org/source/world-development-indicators</a>
</div>
</div>

</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="wdi_report_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="wdi_report_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="wdi_report_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="wdi_report_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="wdi_report_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="wdi_report_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="wdi_report_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="wdi_report_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="wdi_report_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="wdi_report_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: false,

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>